language: java

notifications:
  email:
    on_success: never
    on_failure: always
    
matrix:
  include:
  - os: linux
    dist: trusty
    jdk: oraclejdk11
install: true

# -B enables non interactive mode and disables colors
# -v Display version information WITHOUT stopping build
script: mvn clean install -B -V

before_deploy:
  - git tag -f dodo-snapshot-build
  - git remote add gh 
    https://JanMosigItemis:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh dodo-snapshot-build
  - git remote remove gh

deploy:
  - provider: releases
    skip-cleanup: true
    api_key:
      secure: $GITHUB_API_KEY
    file: target/dodo-1.0.0-SNAPSHOT.jar
    draft: true
    on:
      repo: JanMosigItemis/dodo
      branch: develop
      tags: true
    overwrite: true
    target_commitish: $TRAVIS_COMMIT
  - provider: releases
    skip-cleanup: true
    api_key:
      secure: $GITHUB_API_KEY
    file: target/dodo-1.0.0-SNAPSHOT.jar
    draft: false
    on:
      repo: JanMosigItemis/dodo
      branch: master
      tags: true
    
cache:
  directories:
  - $HOME/.m2
