language: java

notifications:
  email:
    on_success: never
    on_failure: always
    
matrix:
  include:
  - os: linux
    dist: trusty
    jdk: oraclejdk11
install: true

# -B enables non interactive mode and disables colors
# -v Display version information WITHOUT stopping build
script: mvn clean install -B -V

after_success:
    - export TRAVIS_TAG=dodo-snapshot-build
    - git tag $TRAVIS_TAG

deploy:
  - provider: releases
    skip-cleanup: true
    api_key:
      secure: $GITHUB_API_KEY
    file: target/dodo-1.0.0-SNAPSHOT.jar
    overwrite: true
    on:
      repo: JanMosigItemis/dodo
      tags: true
    
cache:
  directories:
  - $HOME/.m2
