language: java

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk11

# Skip the rest of the installation step entirely
install: true

script: mvn install -DskipTests=true -B -V
script: mvn test -B
