if: NOT tag =~ /^(dodo-snapshot-build).*$/
language: java

notifications:
  email:
    on_success: never
    on_failure: always
    
matrix:
  include:
  - os: linux
    dist: trusty
    jdk: oraclejdk11
install: true

# -B enables non interactive mode and disables colors
# -v Display version information WITHOUT stopping build
script: mvn clean install -B -V

# See that the script is not run in isolation, because it changes global env variables.
after_success:
    - . ./.ci/after_success.sh

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_API_KEY
    file: target/dodo-1.0.0-SNAPSHOT.jar
    skip-cleanup: true
    overwrite: true
    on:
      repo: JanMosigItemis/dodo
      tags: true
    
cache:
  directories:
  - $HOME/.m2
